/* ============================================================
   content.ts — the SINGLE content-loading path for the dashboard
   (shallow-frontend program, DR-014; design A2 §2).

   Source selection (Q3, as amended by DR-015):
     - the live bubblegauge content API first — the base URL is
       REUSED from the one existing embedded-endpoint derivation in
       src/bubblegauge.tsx (resolveApiBase: fixed KEY_RE-whitelisted
       subdomain label + the page's parent domain, localhost dev
       base; no query parameter). This module NEVER derives a host
       itself and holds NO host literal; it consumes the already-
       derived product, window.BubbleGauge.apiBase, so the DR-014
       red line "KEY_RE gating stays" keeps exactly one enforcement
       site.
     - else (API unreachable, or a payload that fails validation) the
       same-origin fallback artifact ./content/fallback.json
       (generated by deploy.yml into dist/content/, never committed).

   The four PR-0 hardening contracts, implemented here:
     1. DISCLAIMER GATE + DOM PURGE — grounded content is served to
        renderers only while the page's hard-baked disclaimer element
        is on screen. The gate is fail-closed (starts engaged until
        startDisclaimerGate() confirms the element) and reentrant
        (re-opens when the element returns). On engagement every
        registered purge hook runs so already-rendered grounded
        values leave the DOM.
     2. LAST-KNOWN-GOOD + SPLIT STALE FLAGS — a committed payload is
        never regressed to empty by a failed refresh; staleness is
        tracked per plane (blocks vs slots) so the UI can label each
        independently. Fallback age is carried separately in `asOf`.
     3. SEQ + SINGLE-FLIGHT BOUNDED LOADING — one load in flight at a
        time (callers share the promise); every fetch is bounded by
        an AbortController timeout; a monotonic sequence number makes
        late responses unable to overwrite a newer commit.
     4. RESPONSE-SHAPE VALIDATION — every payload is structurally
        validated at the boundary; a content payload without a
        non-empty disclaimer block NEVER commits (Q7/Q50). Dynamic
        slot text must match the printable-ASCII slot contract;
        violating slots are dropped, never rendered.

   Egress contract (62-security-surface, amended per DR-014 §2):
   the one fetch call site below can only be reached with a URL that
   passed assertContentUrl — the derived apiBase's two content paths,
   or the same-origin relative fallback URL (protocol-relative URLs
   rejected explicitly). No other destination is constructible.
   ============================================================ */

/* ---------- public types ---------- */

export type ContentSourceKind = "live" | "fallback";

export interface ContentBlock {
  kind: string;
  text?: string;
  items?: string[];
  entries?: unknown[];
}

export interface ContentSlot {
  text: string;
  source?: string; // slot provenance from the API (e.g. generator id) — NOT the live|fallback flag
  updated_at?: string;
  purpose?: string;
  constraints?: string;
}

export interface StaleFlags {
  blocks: boolean; // true = blocks shown are last-known-good, not from the latest successful load
  slots: boolean; // same, for dynamic slots — the two planes fail independently (split labels)
}

export interface ContentState {
  status: "idle" | "loading" | "ready" | "error";
  source: ContentSourceKind | null; // drives the Q12 "offline content" badge when "fallback"
  contentVersion: number | null; // monotonic stamp from the payload (provenance display)
  asOf: string | null; // fallback artifact build stamp; null when serving live
  stale: StaleFlags;
  gated: boolean; // true = disclaimer gate engaged; getBlock/getSlot serve nothing
  error: string | null; // last load problem (informational; LKG may still be served)
}

/* ---------- contract constants (asserted by the re-frozen suite) ---------- */

// Same-origin fallback artifact (P3). Relative to the page — never a host.
export const FALLBACK_URL = "./content/fallback.json";
// Content API paths appended to the derived apiBase (shapes are live, PR-1a).
export const CONTENT_DASHBOARD_PATH = "/api/v1/content/dashboard";
export const CONTENT_DYNAMIC_PATH = "/api/v1/content/dynamic";
// The block slug that must carry a non-empty disclaimer for a payload to commit (Q50).
export const DISCLAIMER_SLUG = "site.disclaimer";
// Default selector for the page's hard-baked disclaimer element (red line: stays in the page).
export const DISCLAIMER_SELECTOR = "[data-disclaimer]";
// Dynamic-slot contract: printable ASCII, bounded (largest registry cap is 700 — A2 §3).
export const SLOT_TEXT_RE = /^[ -~]{1,700}$/;

const FETCH_TIMEOUT_MS = 6000;

/* ---------- derived live base (REUSE, not re-derivation) ---------- */

// The subdomain derivation (KEY_RE = /^[a-z0-9-]{1,32}$/ over the embedded label, the parent-
// domain read from location.hostname, the localhost dev fallback) lives in src/bubblegauge.tsx
// resolveApiBase() and ONLY there. bubblegauge.js loads before dashboard.js and publishes the
// derived base as window.BubbleGauge.apiBase (null on a host with no derivable parent, in which
// case this module reads the fallback artifact directly).
function liveBase(): string | null {
  if (typeof window === "undefined") return null;
  const bg = window.BubbleGauge;
  if (!bg || bg.enabled !== true) return null;
  const base = bg.apiBase;
  if (typeof base !== "string" || base.length === 0) return null;
  return base;
}

/* ---------- URL allowlist (contract 4 precondition; A2 §2 same-origin filter) ---------- */

function isSameOriginRelativeUrl(u: string): boolean {
  if (typeof u !== "string" || u.length === 0) return false;
  if (u.slice(0, 2) === "//") return false; // protocol-relative — rejected explicitly (A2 §2)
  if (u.indexOf(":") !== -1) return false; // any scheme (http:, javascript:, data:, …)
  if (u.indexOf("\\") !== -1) return false;
  if (u.indexOf("..") !== -1) return false; // no path escape
  return u.slice(0, 2) === "./"; // relative to the served page only
}

// The single chokepoint every fetch URL must pass. Throws on anything outside the allowlist:
// the two content paths on the derived apiBase, or the same-origin relative fallback artifact.
function assertContentUrl(url: string, base: string | null): string {
  if (base !== null && (url === base + CONTENT_DASHBOARD_PATH || url === base + CONTENT_DYNAMIC_PATH)) {
    return url;
  }
  if (url === FALLBACK_URL && isSameOriginRelativeUrl(url)) return url;
  throw new Error("content fetch blocked: '" + url + "' is outside the content allowlist");
}

/* ---------- bounded fetch (contract 3) ---------- */

interface FetchResult {
  ok: boolean;
  status: number;
  json: unknown;
  error: string | null;
}

// The ONLY fetch call site in this module. Never rejects; always clears its timeout.
function boundedFetch(url: string, base: string | null): Promise<FetchResult> {
  let checked: string;
  try {
    checked = assertContentUrl(url, base);
  } catch (e) {
    return Promise.resolve({ ok: false, status: 0, json: null, error: String((e && e.message) || e) });
  }
  const ctrl = new AbortController();
  const timer = setTimeout(function (): void {
    ctrl.abort();
  }, FETCH_TIMEOUT_MS);
  return fetch(checked, { signal: ctrl.signal, headers: { accept: "application/json" } }).then(
    function (r: Response): Promise<FetchResult> | FetchResult {
      clearTimeout(timer);
      if (!r.ok) return { ok: false, status: r.status, json: null, error: "HTTP " + r.status };
      return r.json().then(
        function (j: unknown): FetchResult {
          return { ok: true, status: r.status, json: j, error: null };
        },
        function (): FetchResult {
          return { ok: false, status: r.status, json: null, error: "invalid JSON" };
        }
      );
    },
    function (e: unknown): FetchResult {
      clearTimeout(timer);
      const msg = e && (e as { message?: unknown }).message;
      return { ok: false, status: 0, json: null, error: String(msg || e) };
    }
  );
}

/* ---------- response-shape validation (contract 4) ---------- */

type Dict = { [k: string]: unknown };

function isPlainObject(x: unknown): x is Dict {
  return typeof x === "object" && x !== null && !Array.isArray(x);
}
function isNonEmptyString(x: unknown): x is string {
  return typeof x === "string" && x.length > 0;
}
function isStringArray(x: unknown): x is string[] {
  if (!Array.isArray(x)) return false;
  for (let i = 0; i < x.length; i++) if (typeof x[i] !== "string") return false;
  return true;
}

function validBlock(b: unknown): boolean {
  if (!isPlainObject(b) || !isNonEmptyString(b.kind)) return false;
  // a block must carry at least one content field of the declared shapes
  if (isNonEmptyString(b.text)) return true;
  if (isStringArray(b.items) && (b.items as string[]).length > 0) return true;
  if (Array.isArray(b.entries) && (b.entries as unknown[]).length > 0) return true;
  return false;
}

type BlockMap = { [slug: string]: ContentBlock };
type SlotMap = { [slug: string]: ContentSlot };

function parseBlockMap(raw: unknown): BlockMap | null {
  if (!isPlainObject(raw)) return null;
  const out: BlockMap = {};
  for (const slug in raw) {
    if (!Object.prototype.hasOwnProperty.call(raw, slug)) continue;
    const b = raw[slug];
    if (!validBlock(b)) continue; // malformed non-disclaimer blocks are dropped, not fatal
    const src = b as Dict;
    const block: ContentBlock = { kind: src.kind as string };
    if (isNonEmptyString(src.text)) block.text = src.text;
    if (isStringArray(src.items)) block.items = Object.freeze((src.items as string[]).slice()) as string[];
    if (Array.isArray(src.entries)) block.entries = Object.freeze((src.entries as unknown[]).slice()) as unknown[];
    out[slug] = Object.freeze(block) as ContentBlock;
  }
  return out;
}

// Dropped (not committed) slots: non-string text, or text outside the printable-ASCII
// bounded contract (^[ -~]{1,700}$ — per-slot caps are enforced server-side; this is the
// client's hard ceiling and charset gate).
function parseSlotMap(raw: unknown): SlotMap | null {
  if (!isPlainObject(raw)) return null;
  const out: SlotMap = {};
  for (const slug in raw) {
    if (!Object.prototype.hasOwnProperty.call(raw, slug)) continue;
    const s = raw[slug];
    if (!isPlainObject(s) || !isNonEmptyString(s.text) || !SLOT_TEXT_RE.test(s.text)) continue;
    const slot: ContentSlot = { text: s.text };
    if (isNonEmptyString(s.source)) slot.source = s.source;
    if (isNonEmptyString(s.updated_at)) slot.updated_at = s.updated_at;
    if (isNonEmptyString(s.purpose)) slot.purpose = s.purpose;
    if (isNonEmptyString(s.constraints)) slot.constraints = s.constraints;
    out[slug] = Object.freeze(slot) as ContentSlot;
  }
  return out;
}

function hasDisclaimer(blocks: BlockMap): boolean {
  const d = blocks[DISCLAIMER_SLUG];
  return !!d && isNonEmptyString(d.text) && d.text.trim().length > 0;
}

function versionOf(data: Dict, envelope: Dict): number | null {
  const v = data.content_version;
  if (typeof v === "number" && isFinite(v)) return v;
  // tolerate the A2-draft location (meta.content_version) so a server-side move is not a breakage
  const meta = envelope.meta;
  if (isPlainObject(meta) && typeof meta.content_version === "number" && isFinite(meta.content_version)) {
    return meta.content_version;
  }
  return null;
}

// GET {base}/api/v1/content/dashboard -> {data:{blocks:{...},content_version},meta}
// Returns null (NEVER commits) when the shape is wrong or the disclaimer block is missing/empty.
function parseLiveDashboard(j: unknown): { blocks: BlockMap; version: number | null } | null {
  if (!isPlainObject(j) || !isPlainObject(j.data)) return null;
  const data = j.data as Dict;
  const blocks = parseBlockMap(data.blocks);
  if (blocks === null || !hasDisclaimer(blocks)) return null;
  return { blocks: blocks, version: versionOf(data, j) };
}

// GET {base}/api/v1/content/dynamic -> {data:{slots:{...},content_version},meta}
// Carries no blocks, hence no disclaimer of its own: commit is additionally gated below on a
// disclaimed block payload already being committed (no state shows grounded content un-disclaimed).
function parseLiveDynamic(j: unknown): { slots: SlotMap; version: number | null } | null {
  if (!isPlainObject(j) || !isPlainObject(j.data)) return null;
  const data = j.data as Dict;
  const slots = parseSlotMap(data.slots);
  if (slots === null) return null;
  return { slots: slots, version: versionOf(data, j) };
}

// ./content/fallback.json -> {as_of, content_version, blocks:{...}, slots:{...}}
// The artifact ALWAYS contains the disclaimer (Q50) and a mandatory as_of stamp (DR-014 §6);
// an artifact violating either never commits.
function parseFallback(
  j: unknown
): { blocks: BlockMap; slots: SlotMap; asOf: string; version: number | null } | null {
  if (!isPlainObject(j)) return null;
  if (!isNonEmptyString(j.as_of)) return null;
  const blocks = parseBlockMap(j.blocks);
  if (blocks === null || !hasDisclaimer(blocks)) return null;
  const slots = j.slots === undefined ? {} : parseSlotMap(j.slots);
  if (slots === null) return null;
  const version = typeof j.content_version === "number" && isFinite(j.content_version) ? j.content_version : null;
  return { blocks: blocks, slots: slots, asOf: j.as_of, version: version };
}

/* ---------- store (contract 2: last-known-good, split stale) ---------- */

const committed: { blocks: BlockMap | null; slots: SlotMap | null } = { blocks: null, slots: null };

// gated starts TRUE: fail-closed until startDisclaimerGate() confirms the baked disclaimer.
let state: ContentState = {
  status: "idle",
  source: null,
  contentVersion: null,
  asOf: null,
  stale: { blocks: false, slots: false },
  gated: true,
  error: null,
};

type Listener = () => void;
const listeners: Listener[] = [];
const purgeHooks: Listener[] = [];

function notify(): void {
  const snap = listeners.slice();
  for (let i = 0; i < snap.length; i++) {
    try {
      snap[i]();
    } catch (e) {
      /* a broken listener must not break the store */
    }
  }
}

function setState(patch: Partial<ContentState>): void {
  state = {
    status: patch.status !== undefined ? patch.status : state.status,
    source: patch.source !== undefined ? patch.source : state.source,
    contentVersion: patch.contentVersion !== undefined ? patch.contentVersion : state.contentVersion,
    asOf: patch.asOf !== undefined ? patch.asOf : state.asOf,
    stale: patch.stale !== undefined ? patch.stale : state.stale,
    gated: patch.gated !== undefined ? patch.gated : state.gated,
    error: patch.error !== undefined ? patch.error : state.error,
  };
}

function committedDisclaimed(): boolean {
  return committed.blocks !== null && hasDisclaimer(committed.blocks);
}

/* ---------- loading (contract 3: seq + single flight) ---------- */

let seq = 0;
let inflight: Promise<ContentState> | null = null;

async function runLoad(mySeq: number): Promise<ContentState> {
  setState({ status: "loading", error: null });
  notify();
  let lastError: string | null = null;
  const base = liveBase();

  if (base !== null) {
    const results = await Promise.all([
      boundedFetch(base + CONTENT_DASHBOARD_PATH, base),
      boundedFetch(base + CONTENT_DYNAMIC_PATH, base),
    ]);
    if (mySeq !== seq) return contentState(); // a newer load owns the store now
    const dash = results[0];
    const dyn = results[1];
    let blocksFresh = false;
    let slotsFresh = false;
    let version: number | null = state.contentVersion;

    if (dash.ok) {
      const parsed = parseLiveDashboard(dash.json);
      if (parsed !== null) {
        committed.blocks = parsed.blocks;
        if (parsed.version !== null) version = parsed.version;
        blocksFresh = true;
      } else {
        lastError = "dashboard content payload rejected (shape/disclaimer)";
      }
    } else {
      lastError = "dashboard content: " + (dash.error || "fetch failed");
    }

    if (dyn.ok) {
      const parsedDyn = parseLiveDynamic(dyn.json);
      if (parsedDyn === null) {
        lastError = appendErr(lastError, "dynamic content payload rejected (shape)");
      } else if (!committedDisclaimed()) {
        // slots never commit without a disclaimed block payload on the books
        lastError = appendErr(lastError, "dynamic slots withheld: no disclaimed content committed");
      } else {
        committed.slots = parsedDyn.slots;
        if (version === null && parsedDyn.version !== null) version = parsedDyn.version;
        slotsFresh = true;
      }
    } else {
      lastError = appendErr(lastError, "dynamic content: " + (dyn.error || "fetch failed"));
    }

    if (blocksFresh || slotsFresh) {
      setState({
        status: "ready",
        source: "live",
        contentVersion: version,
        asOf: null,
        // a plane that did not refresh but still shows last-known-good content is labeled stale
        stale: {
          blocks: !blocksFresh && committed.blocks !== null,
          slots: !slotsFresh && committed.slots !== null,
        },
        error: lastError,
      });
      notify();
      return contentState();
    }
    // the live path produced nothing this round — fall through to the same-origin fallback
  }

  const fb = await boundedFetch(FALLBACK_URL, null);
  if (mySeq !== seq) return contentState();
  if (fb.ok) {
    const parsedFb = parseFallback(fb.json);
    if (parsedFb !== null) {
      committed.blocks = parsedFb.blocks;
      committed.slots = parsedFb.slots;
      setState({
        status: "ready",
        source: "fallback",
        contentVersion: parsedFb.version,
        asOf: parsedFb.asOf,
        stale: { blocks: false, slots: false }, // artifact age is carried by asOf, not stale flags
        error: lastError,
      });
      notify();
      return contentState();
    }
    lastError = appendErr(lastError, "fallback artifact rejected (shape/disclaimer/as_of)");
  } else {
    lastError = appendErr(lastError, "fallback: " + (fb.error || "fetch failed"));
  }

  // contract 2: never regress a committed state to empty — keep last-known-good, label it stale
  if (committed.blocks !== null || committed.slots !== null) {
    setState({
      status: "ready",
      stale: { blocks: committed.blocks !== null, slots: committed.slots !== null },
      error: lastError,
    });
  } else {
    setState({ status: "error", source: null, error: lastError });
  }
  notify();
  return contentState();
}

function appendErr(prev: string | null, next: string): string {
  return prev === null ? next : prev + "; " + next;
}

/* ---------- public API ---------- */

// Kick off (or join) a content load. Single-flight: concurrent callers share one promise;
// each new load bumps the sequence so a straggling older response can never overwrite it.
export function loadContent(): Promise<ContentState> {
  if (inflight !== null) return inflight;
  const mySeq = ++seq;
  const p = runLoad(mySeq).then(
    function (s: ContentState): ContentState {
      if (inflight === p) inflight = null;
      return s;
    },
    function (e: unknown): ContentState {
      // runLoad catches everything internally; this is belt-and-braces
      if (inflight === p) inflight = null;
      setState({ status: committed.blocks !== null || committed.slots !== null ? "ready" : "error", error: String(e) });
      notify();
      return contentState();
    }
  );
  inflight = p;
  return p;
}

// Renderer read path — fail-closed: nothing is served while the disclaimer gate is engaged.
export function getBlock(slug: string): ContentBlock | null {
  if (state.gated || committed.blocks === null) return null;
  const b = committed.blocks[slug];
  return b === undefined ? null : b;
}

export function getSlot(slug: string): ContentSlot | null {
  if (state.gated || committed.slots === null || !committedDisclaimed()) return null;
  const s = committed.slots[slug];
  return s === undefined ? null : s;
}

export function contentState(): ContentState {
  return {
    status: state.status,
    source: state.source,
    contentVersion: state.contentVersion,
    asOf: state.asOf,
    stale: { blocks: state.stale.blocks, slots: state.stale.slots },
    gated: state.gated,
    error: state.error,
  };
}

// Re-render subscription for the tabs (returns the unsubscribe).
export function subscribeContent(fn: Listener): () => void {
  listeners.push(fn);
  return function (): void {
    const i = listeners.indexOf(fn);
    if (i !== -1) listeners.splice(i, 1);
  };
}

// Purge hooks run when the disclaimer gate ENGAGES: consumers must remove already-rendered
// grounded values from the DOM (contract 1). Returns the unregister.
export function registerPurgeHook(fn: Listener): () => void {
  purgeHooks.push(fn);
  return function (): void {
    const i = purgeHooks.indexOf(fn);
    if (i !== -1) purgeHooks.splice(i, 1);
  };
}

/* ---------- disclaimer gate (contract 1) ---------- */

let gateStarted = false;
let gateObserver: MutationObserver | null = null;

function setGated(g: boolean): void {
  if (state.gated === g) return;
  setState({ gated: g });
  if (g) {
    const snap = purgeHooks.slice();
    for (let i = 0; i < snap.length; i++) {
      try {
        snap[i]();
      } catch (e) {
        /* one failing purge hook must not stop the others */
      }
    }
  }
  notify();
}

function disclaimerOnScreen(selector: string): boolean {
  const el = document.querySelector(selector);
  if (el === null) return false;
  if (el.hasAttribute("hidden")) return false;
  if (el.getAttribute("aria-hidden") === "true") return false;
  return true;
}

// Watch the page's hard-baked disclaimer element (red line 5: it stays in the page — this gate
// does not create it, it enforces it). Fail-closed: until this runs, and whenever the element
// is missing/hidden, the store serves nothing. Reentrant: the gate re-opens on restoration.
export function startDisclaimerGate(selector?: string): void {
  if (gateStarted) return;
  gateStarted = true;
  const sel = typeof selector === "string" && selector.length > 0 ? selector : DISCLAIMER_SELECTOR;
  const check = function (): void {
    setGated(!disclaimerOnScreen(sel));
  };
  try {
    gateObserver = new MutationObserver(check);
    gateObserver.observe(document.documentElement, {
      childList: true,
      subtree: true,
      attributes: true,
      attributeFilter: ["hidden", "aria-hidden"],
    });
  } catch (e) {
    gateObserver = null; // no observer available: the initial check below still decides, once
  }
  check();
}
